# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(related_name='_user_follows_+', to='register.User'),
        ),
    ]
