# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-07-26 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180523_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='none.jpg', upload_to='media'),
        ),
    ]
